name: Build and Lint TM4C129 Firmware

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:  # Allow manual triggering

jobs:
  lint:
    runs-on: ubuntu-latest
    continue-on-error: true  # Make linting optional for now
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install linting tools
        run: |
          sudo apt-get update
          sudo apt-get install -y clang-format cppcheck

      - name: Run clang-format check
        run: |
          # Only check src/ and inc/ directories which contain your code
          # Exclude TivaWare and other third-party libraries
          python3 tools/run-clang-format.py --recursive --extensions=c,h src/ inc/

      - name: Run cppcheck static analysis
        run: |
          # Only analyze src/ and inc/ directories which contain your code
          cppcheck --enable=warning,performance,portability --suppress=missingIncludeSystem --error-exitcode=1 \
            --std=c99 --language=c --inline-suppr \
            -I inc/ -I libraries/TivaWare/inc/ -I libraries/TivaWare/driverlib/ \
            src/ inc/

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install ARM toolchain
        run: |
          sudo apt-get update
          sudo apt-get install -y gcc-arm-none-eabi binutils-arm-none-eabi libnewlib-arm-none-eabi cmake ninja-build

      - name: Extract TivaWare
        run: |
          # Create necessary directories
          mkdir -p downloads/tivaware_extracted

          # For CI purposes, we won't actually use the full TivaWare package
          # Instead we'll use only what's necessary from the libraries directory
          if [ ! -d "libraries/TivaWare/driverlib" ]; then
            echo "Error: TivaWare libraries not found. CI will use minimal headers for compilation."
            # Create minimal directory structure for compilation
            mkdir -p libraries/TivaWare/driverlib
            mkdir -p libraries/TivaWare/inc
          fi

      - name: Configure CMake
        run: |
          mkdir -p build
          cd build
          cmake .. -G Ninja

      - name: Build project
        run: |
          cd build
          ninja

      - name: Upload firmware artifact
        uses: actions/upload-artifact@v3
        with:
          name: firmware
          path: |
            build/TM4C129ENCPDT.bin
            build/TM4C129ENCPDT.elf
